# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# port: 4000 // custom port for local development (default is 4000)
# default is -> "/posts/2025/02/14/welcome-to-jekyll"
# you can do that too -> permalink: /blog/:title/
permalink: /:categories/:title/

title: Max Korn | UI & UX Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://links.maxkorn.de" # the base hostname & protocol for your site, e.g. http://example.com
theme-color: "#4ade80" # Used for browser theme-color meta tag

# gravatar: XXX # Gravatar md5 hash
branding: false # Your name will be replaced with your logo if set to true, change your logo here "_includes/svg/logo.svg"

sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
  - jekyll-deployment.md
  - jekyll_server_deployment.md
  - LICENSE.md
  - README.md
  - templating-system.png
  - reference.txt
  - vercel.json
  - cargoboard

analytics:
  enabled: false
  google:
    tracking_id: #Add your Google analytics tracking ID here
