title: Vyshnav Gangadharan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://links.maxkorn.de" # the base hostname & protocol for your site, e.g. http://example.com
theme-color: "#4ade80" # Used for browser theme-color meta tag

# gravatar: XXX # Gravatar md5 hash
branding: false # Your name will be replaced with your logo if set to true, change your logo here "_includes/svg/logo.svg"

sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
  - jekyll-deployment.md
  - jekyll_server_deployment.md
  - LICENSE.md
  - README.md

analytics:
  enabled: false
  google:
    tracking_id: #Add your Google analytics tracking ID here
